import type { Config } from 'tailwindcss'

const config: Config = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
    './src/lib/**/*.{js,ts,jsx,tsx,mdx}',
    './src/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  safelist: [
    'bg-slate-950',
    'bg-slate-900',
    'bg-slate-800',
    'bg-zinc-950',
    'bg-zinc-900',
    'bg-blue-950',
    'bg-blue-900',
    'bg-orange-950',
    'bg-orange-900',
    'bg-gray-950',
    'bg-gray-900',
    'bg-black',
    'bg-navy',
    'border-blue-900/40',
    'border-blue-900/50',
    'border-blue-900/60',
    'border-blue-800/40',
    'border-blue-800/50',
    'border-blue-800/60',
    'border-teal-900/40',
    'border-teal-900/50',
    'border-teal-900/60',
    'border-cyan-900/40',
    'border-cyan-900/50',
    'border-cyan-900/60',
    'border-cyan-800/40',
    'border-cyan-800/50',
    'border-cyan-800/60',
    'border-emerald-900/40',
    'border-emerald-900/50',
    'border-emerald-900/60',
    'border-emerald-950/60',
    'border-emerald-800/40',
    'border-indigo-900/40',
    'border-indigo-800/40',
    'border-indigo-800/50',
    'border-indigo-800/60',
    'border-orange-950/50',
    'border-orange-900/50',
    'border-orange-900/60',
    'border-orange-800/40',
    'border-orange-800/50',
    'border-orange-800/70',
    'border-slate-800',
    'border-slate-700',
    'border-emerald-500/40',
    'border-cyan-400/40',
    'hover:text-teal-400',
    'hover:text-teal-300',
    'hover:text-cyan-400',
    'hover:text-cyan-300',
    'hover:text-emerald-400',
    'hover:text-emerald-300',
    'hover:text-blue-400',
    'hover:text-orange-400',
    'hover:text-orange-300',
    'hover:text-indigo-400',
    'hover:text-indigo-300',
    'bg-teal-500',
    'bg-cyan-500',
    'bg-emerald-500',
    'bg-orange-500',
    'bg-blue-500',
    'bg-indigo-500',
  ],
  theme: {
    extend: {
      colors: {
        'navy': '#071A2B',
        'navy-dark': '#0B2239',
        'navy-royal': '#12395A',
        'gold-primary': '#D4AF37',
        'gold-light': '#F1D77A',
        'gold-soft': '#E8C96A',
        'dark-text': '#111827',
        'muted-text': '#64748B',
        'off-white': '#F7F8FA',
        'teal': '#14B8A6',
        'cyan': '#06B6D4',
      },
      fontFamily: {
        sans: ['Plus Jakarta Sans', '-apple-system', 'BlinkMacSystemFont', 'Segoe UI', 'Roboto', 'sans-serif'],
        mono: ['Plus Jakarta Sans', '-apple-system', 'BlinkMacSystemFont', 'sans-serif'],
      },
      backgroundImage: {
        'gradient-navy': 'linear-gradient(135deg, #071A2B 0%, #0B2239 100%)',
        'gradient-navy-accent': 'linear-gradient(135deg, #071A2B 0%, #12395A 100%)',
        'gradient-gold': 'linear-gradient(135deg, #D4AF37 0%, #F1D77A 100%)',
        'gradient-accent': 'linear-gradient(135deg, #14B8A6 0%, #06B6D4 100%)',
      },
      animation: {
        'float': 'float 6s ease-in-out infinite',
        'float-delayed': 'float 7s ease-in-out infinite 1s',
        'float-slow': 'float 8s ease-in-out infinite',
        'slide-in': 'slide-in 0.5s ease-out',
        'fade-up': 'fade-up 0.6s ease-out',
        'pulse-soft': 'pulse-soft 2s ease-in-out infinite',
        'bounce-soft': 'bounce-soft 2s ease-in-out infinite',
      },
      keyframes: {
        float: {
          '0%, 100%': { transform: 'translateY(0px)' },
          '50%': { transform: 'translateY(-20px)' },
        },
        'float-delayed': {
          '0%, 100%': { transform: 'translateY(0px)' },
          '50%': { transform: 'translateY(-20px)' },
        },
        'slide-in': {
          '0%': { transform: 'translateX(-100%)', opacity: '0' },
          '100%': { transform: 'translateX(0)', opacity: '1' },
        },
        'fade-up': {
          '0%': { transform: 'translateY(20px)', opacity: '0' },
          '100%': { transform: 'translateY(0)', opacity: '1' },
        },
        'pulse-soft': {
          '0%, 100%': { opacity: '1' },
          '50%': { opacity: '0.5' },
        },
        'bounce-soft': {
          '0%, 100%': { transform: 'translateY(0)' },
          '50%': { transform: 'translateY(-10px)' },
        },
      },
      typography: {
        DEFAULT: {
          css: {
            maxWidth: '100%',
            img: {
              maxWidth: '100%',
              height: 'auto',
            },
            table: {
              overflowX: 'auto',
            },
            pre: {
              overflowX: 'auto',
              maxWidth: '100%',
            },
          },
        },
      },
    },
  },
  plugins: [],
}

export default config
